/**
 * 看个电影 · 扩充片库 v2 · 第二部分（欧美剧情/动画/爱情/恐怖/纪录/其他）
 */
(function () {
  if (!window.MOVIES) window.MOVIES = [];

  const EXTRA2 = [
    // ============ 欧美剧情 / 文艺 / 爱情 ============
    { id:"call-me-by-your-name", title:"请以你的名字呼唤我", year:2017, duration:132,
      genres:["爱情","文艺"], moods:["romantic","lonely","calm"],
      weather:["hot","sunny"], env:["bright","hot"], time:["afternoon","evening"],
      people:[1,2], ageMin:16, ageMax:60, rating:8.7,
      desc:"瓜达尼诺意大利夏日。Sufjan Stevens 一响，桃子都跟着哭。",
      tags:["夏日","文艺"], poster:"🍑" },
    { id:"moonlight", title:"月光男孩", year:2016, duration:111,
      genres:["剧情","文艺"], moods:["lonely","down","calm"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:60, rating:7.5,
      desc:"巴里·詹金斯奥斯卡。三幕人生，蓝色像呼吸。",
      tags:["奥斯卡","成长"], poster:"🌊" },
    { id:"manchester-by-sea", title:"海边的曼彻斯特", year:2016, duration:137,
      genres:["剧情","文艺"], moods:["down","lonely","calm"],
      weather:["snowy","cold"], env:["cool","dim"], time:["afternoon","evening"],
      people:[1], ageMin:18, ageMax:99, rating:8.6,
      desc:"\"我心已碎，我无法走出来\"。冬天看会更冷。",
      tags:["奥斯卡","致郁"], poster:"⚓" },
    { id:"lady-bird", title:"伯德小姐", year:2017, duration:94,
      genres:["剧情","喜剧","家庭"], moods:["calm","down","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1],
      ageMin:14, ageMax:60, rating:7.7,
      desc:"格蕾塔·葛韦格出道。每个女孩都是 Lady Bird。",
      tags:["成长","女性视角"], poster:"🌷" },
    { id:"little-women-2019", title:"小妇人", year:2019, duration:135,
      genres:["剧情","家庭","爱情"], moods:["calm","romantic","down"],
      weather:["snowy","cold"], env:["cool","bright"], time:["afternoon","evening"],
      people:[1,2,4], ageMin:12, ageMax:99, rating:8.1,
      desc:"葛韦格 × 罗南。冬日围炉的最佳搭档。",
      tags:["女性","奥斯卡"], poster:"📖" },
    { id:"barbie", title:"芭比", year:2023, duration:114,
      genres:["喜剧","奇幻"], moods:["happy","curious"],
      weather:["sunny","any"], env:["bright"], time:["afternoon","evening"],
      people:[2,3,1], ageMin:14, ageMax:60, rating:7.0,
      desc:"葛韦格粉色狂想。背后藏着锋利的女性宣言。",
      tags:["话题作","粉色"], poster:"💖" },
    { id:"everything-everywhere", title:"瞬息全宇宙", year:2022, duration:139,
      genres:["科幻","奇幻","喜剧","家庭"], moods:["excited","curious","down"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:8.4,
      desc:"杨紫琼七项奥斯卡。多元宇宙下的母女和解，看完会想抱抱妈。",
      tags:["奥斯卡","视觉"], poster:"🥯" },
    { id:"the-fabelmans", title:"造梦之家", year:2022, duration:151,
      genres:["剧情","家庭"], moods:["calm","curious"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1,4],
      ageMin:12, ageMax:99, rating:7.8,
      desc:"斯皮尔伯格半自传。一个少年是如何爱上电影的。",
      tags:["斯皮尔伯格"], poster:"🎞️" },
    { id:"green-book", title:"绿皮书", year:2018, duration:130,
      genres:["剧情","喜剧","治愈"], moods:["happy","calm","down"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1,4],
      ageMin:12, ageMax:99, rating:8.9,
      desc:"奥斯卡。公路 + 跨种族友情 + 炸鸡。下饭治愈。",
      tags:["奥斯卡","治愈"], poster:"🚗" },
    { id:"the-help", title:"相助", year:2011, duration:146,
      genres:["剧情","家庭"], moods:["down","happy","calm"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,4],
      ageMin:14, ageMax:99, rating:8.7,
      desc:"\"You is kind, you is smart, you is important.\"",
      tags:["治愈","女性"], poster:"📚" },
    { id:"dead-poets-society", title:"死亡诗社", year:1989, duration:128,
      genres:["剧情","文艺"], moods:["down","calm","excited"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:14, ageMax:99, rating:9.1,
      desc:"\"O Captain! My Captain!\" 罗宾·威廉姆斯永垂不朽。",
      tags:["励志","成长"], poster:"📖" },
    { id:"good-will-hunting", title:"心灵捕手", year:1997, duration:126,
      genres:["剧情","治愈"], moods:["down","calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:14, ageMax:99, rating:8.9,
      desc:"\"It's not your fault.\" 公园长椅那段封神。",
      tags:["治愈"], poster:"🌳" },
    { id:"about-time", title:"时空恋旅人", year:2013, duration:123,
      genres:["爱情","奇幻","治愈","家庭"], moods:["romantic","down","calm"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[1,2,4],
      ageMin:14, ageMax:99, rating:8.9,
      desc:"会穿越的男人和会平凡的生活。爱情电影里最暖那部。",
      tags:["治愈","约会向"], poster:"⏰" },
    { id:"love-actually", title:"真爱至上", year:2003, duration:135,
      genres:["爱情","喜剧","家庭"], moods:["romantic","happy"],
      weather:["snowy","cold"], env:["bright","cool"], time:["evening","night"],
      people:[2,4,1], ageMin:12, ageMax:99, rating:8.6,
      desc:"圣诞必看。10 段爱情同时盛开。",
      tags:["圣诞","合家欢"], poster:"🎄" },
    { id:"notting-hill", title:"诺丁山", year:1999, duration:124,
      genres:["爱情","喜剧"], moods:["romantic","happy"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,2],
      ageMin:14, ageMax:60, rating:7.8,
      desc:"休·格兰特 × 罗伯茨。\"I'm just a girl\"。",
      tags:["浪漫喜剧"], poster:"🌸" },
    { id:"500-days-of-summer", title:"和莎莫的500天", year:2009, duration:95,
      genres:["爱情","喜剧","文艺"], moods:["lonely","down","romantic"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:14, ageMax:60, rating:8.0,
      desc:"分手疗伤片。看完明白这不是恋爱电影。",
      tags:["分手必看"], poster:"☀️" },
    { id:"before-sunset", title:"爱在日落黄昏时", year:2004, duration:80,
      genres:["爱情","文艺"], moods:["romantic","calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["afternoon","evening"],
      people:[1,2], ageMin:16, ageMax:60, rating:9.0,
      desc:"九年后再相遇。爱在三部曲第二部。",
      tags:["爱在三部曲"], poster:"🌇" },
    { id:"before-midnight", title:"爱在午夜降临前", year:2013, duration:109,
      genres:["爱情","文艺"], moods:["lonely","calm","down"],
      weather:["any"], env:["bright","cool"], time:["evening","night"], people:[1,2],
      ageMin:18, ageMax:99, rating:8.7,
      desc:"九年再九年。这次他们吵架了。",
      tags:["爱在三部曲"], poster:"🌙" },
    { id:"silver-linings", title:"乌云背后的幸福线", year:2012, duration:122,
      genres:["爱情","剧情","喜剧"], moods:["down","romantic","happy"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.0,
      desc:"劳伦斯小姐封后。两个精神病也能跳出最棒的舞。",
      tags:["奥斯卡","治愈"], poster:"💃" },
    { id:"eternal-sunshine", title:"暖暖内含光", year:2004, duration:108,
      genres:["爱情","科幻","文艺"], moods:["romantic","lonely","down"],
      weather:["snowy","cold"], env:["dim","cool"], time:["evening","night"],
      people:[1], ageMin:16, ageMax:60, rating:8.5,
      desc:"金凯瑞 × 凯特·温斯莱特。如果能删掉这段记忆，你还会再爱一次吗？",
      tags:["神片","分手必看"], poster:"🧠" },
    { id:"the-pursuit", title:"当幸福来敲门", year:2006, duration:117,
      genres:["剧情","治愈","家庭"], moods:["down","stressed"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,4],
      ageMin:10, ageMax:99, rating:9.2,
      desc:"威尔·史密斯 + 亲儿子。地铁站洗手间那段会哭。",
      tags:["励志","催泪"], poster:"💼" },
    { id:"million-dollar-baby", title:"百万美元宝贝", year:2004, duration:132,
      genres:["剧情"], moods:["down","calm"],
      weather:["any"], env:["dim"], time:["evening"], people:[1],
      ageMin:16, ageMax:99, rating:8.7,
      desc:"伊斯特伍德。后半小时一拳一拳打在心上。",
      tags:["奥斯卡"], poster:"🥊" },
    { id:"a-star-is-born", title:"一个明星的诞生", year:2018, duration:136,
      genres:["爱情","剧情"], moods:["romantic","down"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,2],
      ageMin:16, ageMax:60, rating:7.6,
      desc:"Lady Gaga × 库珀。Shallow 一响泪光闪闪。",
      tags:["音乐","催泪"], poster:"🎤" },
    { id:"bohemian-rhapsody", title:"波西米亚狂想曲", year:2018, duration:135,
      genres:["剧情","文艺"], moods:["excited","down"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:12, ageMax:99, rating:8.7,
      desc:"皇后乐队传记。Live Aid 那段独自看也会站起来。",
      tags:["音乐","传记"], poster:"🎸" },
    { id:"rocketman", title:"火箭人", year:2019, duration:121,
      genres:["剧情","文艺"], moods:["excited","down","romantic"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:60, rating:7.7,
      desc:"埃尔顿·约翰传记歌舞片。色彩饱和度比 Gaga 还高。",
      tags:["音乐","传记"], poster:"🚀" },
    { id:"king-speech", title:"国王的演讲", year:2010, duration:118,
      genres:["剧情","文艺"], moods:["calm","down"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:12, ageMax:99, rating:8.3,
      desc:"科林·费尔斯奥斯卡。一个口吃的国王和他的语言老师。",
      tags:["奥斯卡","治愈"], poster:"👑" },
    { id:"the-reader", title:"朗读者", year:2008, duration:124,
      genres:["爱情","文艺","剧情"], moods:["lonely","romantic","calm"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:8.5,
      desc:"凯特·温斯莱特封后。岁月给爱情上的最厚的灰。",
      tags:["奥斯卡","文艺"], poster:"📚" },
    { id:"the-revenant", title:"荒野猎人", year:2015, duration:156,
      genres:["剧情","冒险","动作"], moods:["stressed","curious"],
      weather:["snowy","cold"], env:["dim","cool"], time:["evening","night"],
      people:[1,3], ageMin:18, ageMax:60, rating:8.0,
      desc:"小李子终于拿奥斯卡。雪地里硬扛 156 分钟。",
      tags:["小李子","硬核"], poster:"🐻" },
    { id:"the-wolf-of-wall", title:"华尔街之狼", year:2013, duration:180,
      genres:["剧情","犯罪","喜剧"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"小李子 + 老马。\"Sell me this pen.\"",
      tags:["斯科塞斯","小李子"], poster:"💸" },
    { id:"there-will-be-blood", title:"血色将至", year:2007, duration:158,
      genres:["剧情","文艺"], moods:["calm","curious"],
      weather:["any"], env:["dim"], time:["evening"], people:[1],
      ageMin:18, ageMax:99, rating:8.0,
      desc:"PT 安德森。\"I drink your milkshake!\"",
      tags:["PTA"], poster:"🛢️" },
    { id:"phantom-thread", title:"魅影缝匠", year:2017, duration:130,
      genres:["爱情","文艺"], moods:["romantic","calm","curious"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1,2],
      ageMin:18, ageMax:60, rating:7.4,
      desc:"DDL 退休前最后一作。一针一线全是控制欲。",
      tags:["PTA","时装"], poster:"🧵" },
    { id:"the-grand-budapest-2", title:"法兰西特派", year:2021, duration:108,
      genres:["喜剧","文艺"], moods:["calm","curious","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1],
      ageMin:14, ageMax:60, rating:7.4,
      desc:"韦斯·安德森又一糖果盒。每一帧都强迫症友好。",
      tags:["韦斯安德森"], poster:"📰" },
    { id:"asteroid-city", title:"小行星城", year:2023, duration:105,
      genres:["喜剧","文艺","科幻"], moods:["calm","curious"],
      weather:["hot","sunny"], env:["hot","bright"], time:["afternoon"], people:[1],
      ageMin:14, ageMax:60, rating:7.0,
      desc:"韦斯安德森色卡再次发力。",
      tags:["韦斯安德森"], poster:"🌵" },
    { id:"the-favourite", title:"宠儿", year:2018, duration:119,
      genres:["剧情","喜剧"], moods:["curious"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:7.1,
      desc:"兰斯莫斯三女王宫斗。鱼眼镜头看到怀疑人生。",
      tags:["奥斯卡","女性"], poster:"🐰" },
    { id:"poor-things", title:"可怜的东西", year:2023, duration:141,
      genres:["剧情","奇幻","科幻"], moods:["curious","happy"],
      weather:["any"], env:["dim","bright"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:7.7,
      desc:"兰斯莫斯 × 艾玛·斯通。蒸汽朋克版 \"夏娃成长史\"。",
      tags:["奥斯卡"], poster:"🧪" },

    // ============ 动画补强（皮克斯/迪士尼/梦工厂） ============
    { id:"wall-e", title:"机器人总动员", year:2008, duration:98,
      genres:["动画","科幻","爱情","治愈"], moods:["lonely","romantic","calm"],
      weather:["any"], env:["dim","cool"], time:["evening"], people:[4,1,2],
      ageMin:5, ageMax:99, rating:9.3,
      desc:"皮克斯无声前 30 分钟封神。地球最后的两个生命体在跳舞。",
      tags:["皮克斯","治愈"], poster:"🤖" },
    { id:"up", title:"飞屋环游记", year:2009, duration:96,
      genres:["动画","家庭","冒险","治愈"], moods:["down","romantic","calm"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:9.0,
      desc:"皮克斯开头 10 分钟就把你的眼泪偷走。",
      tags:["皮克斯","催泪"], poster:"🎈" },
    { id:"toy-story-3", title:"玩具总动员3", year:2010, duration:103,
      genres:["动画","家庭","冒险"], moods:["down","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:9.1,
      desc:"皮克斯。所有童年的告别，都在这部里。",
      tags:["皮克斯","催泪"], poster:"🤠" },
    { id:"finding-nemo", title:"海底总动员", year:2003, duration:100,
      genres:["动画","家庭","冒险","治愈"], moods:["calm","happy"],
      weather:["any"], env:["bright"], time:["afternoon"], people:[4,1],
      ageMin:5, ageMax:99, rating:8.4,
      desc:"皮克斯。父爱跨越整个大洋。",
      tags:["皮克斯","亲子"], poster:"🐠" },
    { id:"ratatouille", title:"美食总动员", year:2007, duration:111,
      genres:["动画","家庭","治愈"], moods:["calm","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:8.8,
      desc:"皮克斯。Anyone can cook。下饭。",
      tags:["皮克斯","下饭"], poster:"🐀" },
    { id:"frozen", title:"冰雪奇缘", year:2013, duration:102,
      genres:["动画","家庭","奇幻"], moods:["happy"],
      weather:["snowy","cold"], env:["cool","bright"], time:["afternoon","evening"],
      people:[4], ageMin:3, ageMax:99, rating:8.4,
      desc:"Let it go. 全球小朋友 KTV 必备。",
      tags:["迪士尼","亲子"], poster:"❄️" },
    { id:"zootopia", title:"疯狂动物城", year:2016, duration:108,
      genres:["动画","家庭","喜剧"], moods:["happy","curious"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:9.2,
      desc:"迪士尼。兔子警察 + 树懒柜员，下饭神片。",
      tags:["迪士尼","下饭"], poster:"🐰" },
    { id:"how-to-train-dragon", title:"驯龙高手", year:2010, duration:98,
      genres:["动画","家庭","冒险"], moods:["happy","calm"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:8.7,
      desc:"梦工厂。配乐一响整个人飞起来。",
      tags:["梦工厂","亲子"], poster:"🐲" },
    { id:"shrek", title:"怪物史莱克", year:2001, duration:90,
      genres:["动画","喜剧","家庭"], moods:["happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,3],
      ageMin:5, ageMax:99, rating:8.5,
      desc:"梦工厂叛逆童话。",
      tags:["梦工厂","合家欢"], poster:"💚" },
    { id:"the-lion-king", title:"狮子王", year:1994, duration:88,
      genres:["动画","家庭","冒险"], moods:["down","happy"],
      weather:["sunny","hot"], env:["bright","hot"], time:["afternoon"],
      people:[4], ageMin:5, ageMax:99, rating:9.1,
      desc:"Hakuna Matata。三代人的童年。",
      tags:["迪士尼","经典"], poster:"🦁" },
    { id:"encanto", title:"魔法满屋", year:2021, duration:102,
      genres:["动画","家庭","奇幻"], moods:["happy","calm"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4],
      ageMin:5, ageMax:99, rating:7.5,
      desc:"\"We don't talk about Bruno.\" BGM 中毒。",
      tags:["迪士尼"], poster:"🏠" },
    { id:"puss-in-boots", title:"穿靴子的猫2", year:2022, duration:102,
      genres:["动画","家庭","冒险"], moods:["happy","excited","down"],
      weather:["any"], env:["bright"], time:["evening"], people:[4,3,1],
      ageMin:6, ageMax:99, rating:8.4,
      desc:"梦工厂逆袭。9 条命剩 1 条，给所有焦虑的成年人。",
      tags:["梦工厂"], poster:"🐱" },
    { id:"klaus", title:"克劳斯：圣诞节的秘密", year:2019, duration:96,
      genres:["动画","家庭","治愈"], moods:["calm","down","happy"],
      weather:["snowy","cold"], env:["cool"], time:["evening"], people:[4,1],
      ageMin:5, ageMax:99, rating:8.7,
      desc:"网飞。手绘风光照得见温柔。",
      tags:["圣诞","治愈"], poster:"🎅" },
    { id:"the-red-turtle", title:"红海龟", year:2016, duration:80,
      genres:["动画","治愈","文艺"], moods:["lonely","calm"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:10, ageMax:99, rating:7.4,
      desc:"吉卜力 + 法国。无对白，纯画面治愈。",
      tags:["吉卜力","治愈"], poster:"🐢" },
    { id:"flow", title:"流浪猫斯凯莱", year:2024, duration:84,
      genres:["动画","治愈","冒险"], moods:["calm","lonely"],
      weather:["rainy","any"], env:["dim","cool"], time:["evening"], people:[1,4],
      ageMin:5, ageMax:99, rating:8.1,
      desc:"拉脱维亚奇迹动画。一只猫 + 一条船 + 没有对白。",
      tags:["独立动画","治愈"], poster:"🐈" },

    // ============ 悬疑 / 恐怖 / 犯罪 ============
    { id:"se7en", title:"七宗罪", year:1995, duration:127,
      genres:["悬疑","犯罪"], moods:["curious","stressed"],
      weather:["rainy"], env:["dim"], time:["night","latenight"], people:[1],
      ageMin:18, ageMax:60, rating:8.7,
      desc:"芬奇。\"What's in the box?\"",
      tags:["芬奇","cult"], poster:"📦" },
    { id:"fight-club", title:"搏击俱乐部", year:1999, duration:139,
      genres:["剧情","悬疑"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1],
      ageMin:18, ageMax:60, rating:9.0,
      desc:"芬奇 + 皮特 + 诺顿。第一条规则：不要讨论搏击俱乐部。",
      tags:["芬奇","神片"], poster:"🥊" },
    { id:"gone-girl", title:"消失的爱人", year:2014, duration:149,
      genres:["悬疑","犯罪"], moods:["curious"],
      weather:["any"], env:["dim"], time:["night"], people:[1,2],
      ageMin:18, ageMax:60, rating:8.7,
      desc:"芬奇 × 派克。婚姻恐怖片之巅。",
      tags:["芬奇"], poster:"💍" },
    { id:"prisoners", title:"囚徒", year:2013, duration:153,
      genres:["悬疑","犯罪"], moods:["stressed","curious"],
      weather:["rainy","cold"], env:["dim"], time:["night"], people:[1],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"维伦纽瓦。一个父亲失去女儿后会变成什么。",
      tags:["维伦纽瓦"], poster:"🔒" },
    { id:"shutter-island", title:"禁闭岛", year:2010, duration:138,
      genres:["悬疑","犯罪"], moods:["curious","stressed"],
      weather:["rainy","cold"], env:["dim"], time:["night"], people:[1],
      ageMin:18, ageMax:60, rating:8.8,
      desc:"小李子 + 老马。结尾那句话比鬼还吓人。",
      tags:["斯科塞斯","小李子"], poster:"🏝️" },
    { id:"silence-of-the-lambs", title:"沉默的羔羊", year:1991, duration:118,
      genres:["悬疑","恐怖","犯罪"], moods:["curious","stressed"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1],
      ageMin:18, ageMax:60, rating:8.8,
      desc:"汉尼拔的眼神能让奥斯卡为他停留。",
      tags:["奥斯卡","cult"], poster:"🦋" },
    { id:"hereditary", title:"遗传厄运", year:2018, duration:127,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["any"], env:["dim"], time:["latenight"], people:[1,2],
      ageMin:18, ageMax:55, rating:7.5,
      desc:"阿里·艾斯特。近 10 年最让人睡不着的恐怖片。",
      tags:["A24","邪典"], poster:"🪆" },
    { id:"midsommar", title:"仲夏夜惊魂", year:2019, duration:148,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["sunny","hot"], env:["bright","hot"], time:["evening"], people:[1],
      ageMin:18, ageMax:55, rating:7.1,
      desc:"阿里·艾斯特。白天的恐怖反而更瘆人。",
      tags:["A24","cult"], poster:"🌻" },
    { id:"the-witch", title:"女巫", year:2015, duration:92,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["cold"], env:["dim","cool"], time:["latenight"], people:[1],
      ageMin:18, ageMax:55, rating:7.0,
      desc:"罗伯特·艾格斯。17 世纪英语 + 山羊 + 烧脑。",
      tags:["A24"], poster:"🐐" },
    { id:"get-out", title:"逃出绝命镇", year:2017, duration:104,
      genres:["恐怖","悬疑"], moods:["curious","stressed"],
      weather:["any"], env:["bright","cool"], time:["evening","night"], people:[1,3],
      ageMin:18, ageMax:55, rating:7.8,
      desc:"乔丹·皮尔。把种族议题做成 cult 神作。",
      tags:["A24","新派恐怖"], poster:"🫖" },
    { id:"a-quiet-place", title:"寂静之地", year:2018, duration:90,
      genres:["恐怖","科幻"], moods:["stressed","curious"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1,2],
      ageMin:14, ageMax:60, rating:7.8,
      desc:"全程不许出声，看的过程都不敢吃爆米花。",
      tags:["新派恐怖"], poster:"🤫" },
    { id:"the-conjuring", title:"招魂", year:2013, duration:112,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["any"], env:["dim"], time:["latenight"], people:[1,3],
      ageMin:18, ageMax:50, rating:7.6,
      desc:"温子仁惊吓密度爆表。",
      tags:["温子仁"], poster:"👻" },
    { id:"sinister", title:"险恶", year:2012, duration:110,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["any"], env:["dim"], time:["latenight"], people:[1],
      ageMin:18, ageMax:50, rating:6.8,
      desc:"传闻医学测心率最吓人那部。",
      tags:["惊悚"], poster:"📼" },
    { id:"smile", title:"危笑", year:2022, duration:115,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["any"], env:["dim"], time:["latenight"], people:[1,3],
      ageMin:18, ageMax:50, rating:6.7,
      desc:"年度最让人开屏不敢笑的电影。",
      tags:["新派恐怖"], poster:"😬" },

    // ============ 纪录 / 治愈 / 文艺 / 其他 ============
    { id:"man-on-wire", title:"走钢丝的人", year:2008, duration:94,
      genres:["纪录","治愈"], moods:["calm","curious","excited"],
      weather:["any"], env:["bright"], time:["evening"], people:[1],
      ageMin:14, ageMax:99, rating:8.5,
      desc:"奥斯卡纪录片。在世贸双子塔之间走 8 趟。",
      tags:["纪录片"], poster:"🏗️" },
    { id:"won-t-you-be-my-neighbor", title:"与我为邻", year:2018, duration:94,
      genres:["纪录","治愈"], moods:["calm","down"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,4],
      ageMin:8, ageMax:99, rating:8.5,
      desc:"罗杰斯先生纪录片。世界很糟，但他真的存在过。",
      tags:["纪录片","治愈"], poster:"🌈" },
    { id:"free-solo", title:"徒手攀岩", year:2018, duration:100,
      genres:["纪录","冒险"], moods:["excited","stressed","curious"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,3],
      ageMin:12, ageMax:60, rating:8.9,
      desc:"奥斯卡纪录片。看着都觉得手汗。",
      tags:["纪录片","极限"], poster:"🧗" },
    { id:"my-neighbors-the-yamadas", title:"我的邻居山田君", year:1999, duration:104,
      genres:["动画","治愈","家庭","喜剧"], moods:["happy","calm"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4],
      ageMin:5, ageMax:99, rating:7.5,
      desc:"高畑勋水彩画风。一家人的鸡毛蒜皮也是诗。",
      tags:["吉卜力","治愈"], poster:"🎏" },
    { id:"my-octopus-teacher", title:"我的章鱼老师", year:2020, duration:85,
      genres:["纪录","治愈"], moods:["calm","lonely"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:10, ageMax:99, rating:8.4,
      desc:"网飞纪录片。一个男人和一只章鱼的友谊。",
      tags:["纪录片","治愈"], poster:"🐙" },
    { id:"sing-street", title:"初恋这首情歌", year:2016, duration:106,
      genres:["爱情","喜剧","治愈"], moods:["happy","romantic","down"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,2],
      ageMin:12, ageMax:60, rating:8.2,
      desc:"约翰·卡尼。一个少年为追女孩组乐队的故事。",
      tags:["音乐","治愈"], poster:"🎸" },
    { id:"begin-again", title:"再次出发之纽约遇见你", year:2013, duration:104,
      genres:["爱情","治愈"], moods:["romantic","down","calm"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.5,
      desc:"约翰·卡尼。耳机共享的男女主，纽约夜风都是温柔的。",
      tags:["音乐","治愈"], poster:"🎧" },
    { id:"once", title:"曾经", year:2007, duration:86,
      genres:["爱情","治愈","文艺"], moods:["lonely","romantic","calm"],
      weather:["rainy","any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:14, ageMax:60, rating:8.4,
      desc:"约翰·卡尼三部曲之首。Falling Slowly 是一辈子的 BGM。",
      tags:["音乐","治愈"], poster:"🎶" },
    { id:"chef", title:"落魄大厨", year:2014, duration:114,
      genres:["治愈","喜剧","家庭"], moods:["happy","calm","stressed"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,4],
      ageMin:12, ageMax:99, rating:8.0,
      desc:"美食 + 公路 + 父子。下班直接看，馋。",
      tags:["下饭","治愈"], poster:"🌮" },
    { id:"julie-julia", title:"朱莉与朱莉娅", year:2009, duration:123,
      genres:["治愈","喜剧","家庭"], moods:["calm","stressed","happy"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,2],
      ageMin:14, ageMax:99, rating:7.7,
      desc:"梅丽尔·斯特里普做法餐。看完想下厨。",
      tags:["下饭","治愈"], poster:"🍲" },
    { id:"midnight-paris", title:"午夜巴黎", year:2011, duration:94,
      genres:["爱情","奇幻","文艺"], moods:["romantic","calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["evening","night"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.1,
      desc:"伍迪·艾伦。一个写作者半夜穿越回 20 年代的巴黎。",
      tags:["伍迪艾伦","巴黎"], poster:"🍷" },
    { id:"vicky-cristina", title:"午夜巴塞罗那", year:2008, duration:96,
      genres:["爱情","喜剧","文艺"], moods:["romantic","calm"],
      weather:["hot","sunny"], env:["bright","hot"], time:["afternoon","evening"],
      people:[1,2], ageMin:18, ageMax:60, rating:7.7,
      desc:"伍迪·艾伦。三角恋写成西班牙红酒。",
      tags:["伍迪艾伦"], poster:"💋" },
    { id:"frances-ha", title:"弗兰西丝·哈", year:2012, duration:86,
      genres:["喜剧","文艺"], moods:["lonely","calm","down"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1],
      ageMin:18, ageMax:60, rating:7.9,
      desc:"诺亚·鲍姆巴赫 × 葛韦格。黑白画面里 27 岁的纽约。",
      tags:["独立","文艺"], poster:"⚪" },
    { id:"marriage-story", title:"婚姻故事", year:2019, duration:137,
      genres:["剧情","爱情","文艺"], moods:["down","calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:18, ageMax:99, rating:8.6,
      desc:"鲍姆巴赫。亚当·德赖弗那段独白看完心痛半年。",
      tags:["独立"], poster:"📑" },
    { id:"the-banshees", title:"伊尼舍林的报丧女妖", year:2022, duration:114,
      genres:["剧情","喜剧","文艺"], moods:["down","calm","lonely"],
      weather:["cloudy","any"], env:["cool"], time:["evening"], people:[1],
      ageMin:18, ageMax:99, rating:7.5,
      desc:"马丁·麦克唐纳。\"我不喜欢你了。\" 友谊版分手电影。",
      tags:["奥斯卡"], poster:"🍻" },
    { id:"banshee-2", title:"伪装者", year:2014, duration:122,
      genres:["剧情","悬疑"], moods:["curious","calm"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"\"我们之中，哪个才是模仿者？\" 一颗安静的子弹。",
      tags:["独立"], poster:"🃏" }
  ];

  window.MOVIES.push(...EXTRA2);
})();
