/**
 * 看个电影 · 扩充片库 v2 · 第一部分（华语 + 日韩 + 部分欧美爆米花）
 */
(function () {
  if (!window.MOVIES) window.MOVIES = [];

  const EXTRA = [
    // ============ 华语经典 / 近年 ============
    { id:"farewell-concubine", title:"霸王别姬", year:1993, duration:171,
      genres:["文艺","爱情","剧情"], moods:["lonely","calm","curious"],
      weather:["any"], env:["dim"], time:["night","evening"], people:[1],
      ageMin:18, ageMax:99, rating:9.6,
      desc:"陈凯歌华语影史天花板。一笑万古春，张国荣那一眼是永恒。",
      tags:["华语经典","张国荣","史诗"], poster:"🎭" },
    { id:"in-the-mood-for-love", title:"花样年华", year:2000, duration:98,
      genres:["爱情","文艺"], moods:["lonely","romantic","calm"],
      weather:["rainy","cloudy"], env:["dim","cool"], time:["evening","night"],
      people:[1,2], ageMin:16, ageMax:99, rating:8.7,
      desc:"王家卫旗袍美学顶点。慢摇升格，60 年代香港的雨夜湿透你。",
      tags:["王家卫","氛围感"], poster:"🌹" },
    { id:"chungking-express", title:"重庆森林", year:1994, duration:102,
      genres:["爱情","文艺","喜剧"], moods:["lonely","romantic","calm"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1,2],
      ageMin:16, ageMax:99, rating:8.8,
      desc:"王家卫凌晨三点的香港。凤梨罐头和加州梦，孤独得很时髦。",
      tags:["王家卫","金城武","梁朝伟"], poster:"🍍" },
    { id:"happy-together-wkw", title:"春光乍泄", year:1997, duration:96,
      genres:["爱情","文艺"], moods:["lonely","romantic","down"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1],
      ageMin:18, ageMax:99, rating:8.9,
      desc:"王家卫南美双男主。不如我们从头来过。",
      tags:["王家卫","张国荣","梁朝伟"], poster:"💃" },
    { id:"a-chinese-odyssey", title:"大话西游：大圣娶亲", year:1995, duration:95,
      genres:["喜剧","爱情","奇幻"], moods:["down","romantic","lonely"],
      weather:["any"], env:["dim"], time:["night"], people:[1,2,3],
      ageMin:14, ageMax:99, rating:9.2,
      desc:"周星驰最会让人哭的喜剧。曾经有一份真挚的爱情……。",
      tags:["星爷","爱情神片","台词封神"], poster:"🐒" },
    { id:"god-of-cookery", title:"食神", year:1996, duration:91,
      genres:["喜剧","家庭"], moods:["happy","stressed"],
      weather:["any"], env:["bright"], time:["evening","night"],
      people:[3,4], ageMin:10, ageMax:99, rating:8.5,
      desc:"星爷下饭片。叉烧饭 + 黯然销魂饭，再丧也能吃下去。",
      tags:["星爷","下饭"], poster:"🍚" },
    { id:"shaolin-soccer", title:"少林足球", year:2001, duration:113,
      genres:["喜剧","动作"], moods:["happy","stressed","excited"],
      weather:["any"], env:["bright"], time:["evening","night"],
      people:[3,4], ageMin:8, ageMax:99, rating:8.3,
      desc:"做人没有梦想跟咸鱼有什么分别。",
      tags:["星爷","励志"], poster:"⚽" },
    { id:"infernal-affairs", title:"无间道", year:2002, duration:101,
      genres:["悬疑","犯罪","动作"], moods:["curious","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:16, ageMax:99, rating:9.3,
      desc:"港片巅峰。梁朝伟 vs 刘德华，给我三年时间。",
      tags:["港片","双雄"], poster:"🕶️" },
    { id:"a-better-tomorrow", title:"英雄本色", year:1986, duration:95,
      genres:["动作","犯罪"], moods:["excited","down"],
      weather:["any"], env:["dim"], time:["night"], people:[3,1],
      ageMin:14, ageMax:99, rating:8.4,
      desc:"小马哥风衣双枪美元烧烟。吴宇森暴力美学的源头。",
      tags:["吴宇森","港片"], poster:"🚬" },
    { id:"hero", title:"英雄", year:2002, duration:120,
      genres:["动作","奇幻","文艺"], moods:["curious","calm"],
      weather:["any"], env:["dim","bright"], time:["evening"], people:[1,3],
      ageMin:12, ageMax:99, rating:7.8,
      desc:"张艺谋色彩美学武侠。红黄蓝绿白，每一段配一种情绪。",
      tags:["张艺谋","视觉系"], poster:"🗡️" },
    { id:"crouching-tiger", title:"卧虎藏龙", year:2000, duration:120,
      genres:["动作","爱情","奇幻"], moods:["calm","romantic","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,2],
      ageMin:12, ageMax:99, rating:8.4,
      desc:"李安奥斯卡四金。竹林斗剑那段一辈子忘不掉。",
      tags:["李安","武侠"], poster:"🎋" },
    { id:"the-mermaid", title:"美人鱼", year:2016, duration:94,
      genres:["喜剧","奇幻","爱情"], moods:["happy"],
      weather:["any"], env:["bright"], time:["evening"], people:[4,3],
      ageMin:8, ageMax:99, rating:6.8,
      desc:"星爷晚期作品。轻松爆笑，全家可看。",
      tags:["星爷","合家欢"], poster:"🧜" },
    { id:"wolf-warrior-2", title:"战狼2", year:2017, duration:123,
      genres:["动作","冒险"], moods:["excited","stressed"],
      weather:["hot","sunny"], env:["bright"], time:["evening","night"],
      people:[3,4], ageMin:12, ageMax:99, rating:7.0,
      desc:"国产硬汉爽片代表。",
      tags:["爽片","国产"], poster:"🪖" },
    { id:"wandering-earth-2", title:"流浪地球2", year:2023, duration:173,
      genres:["科幻","冒险","动作"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"],
      people:[3,4,1], ageMin:12, ageMax:99, rating:8.3,
      desc:"郭帆国产科幻硬扛之作。",
      tags:["国产科幻"], poster:"🌍" },
    { id:"hi-mom", title:"你好，李焕英", year:2021, duration:128,
      genres:["喜剧","家庭","文艺"], moods:["down","calm"],
      weather:["any"], env:["any"], time:["evening","night"],
      people:[4,1], ageMin:8, ageMax:99, rating:7.8,
      desc:"贾玲写给妈妈。前半笑得肚子疼，后半哭得鼻塞。",
      tags:["催泪","亲情"], poster:"🌷" },
    { id:"the-farewell", title:"别告诉她", year:2019, duration:100,
      genres:["家庭","文艺"], moods:["calm","lonely","down"],
      weather:["any"], env:["cool","bright"], time:["afternoon"], people:[1,4],
      ageMin:14, ageMax:99, rating:7.5,
      desc:"王子逸 × 奥卡菲娜。一场假婚礼，把跨代亲情拍得淡而疼。",
      tags:["家庭"], poster:"🥢" },
    { id:"long-day-journey", title:"地球最后的夜晚", year:2018, duration:138,
      genres:["文艺","爱情"], moods:["lonely","calm"],
      weather:["rainy","any"], env:["dim","cool"], time:["latenight"], people:[1],
      ageMin:18, ageMax:99, rating:6.8,
      desc:"毕赣长镜头。后半段一镜到底要戴 3D 眼镜。",
      tags:["毕赣","氛围"], poster:"🌌" },
    { id:"raise-red-lantern", title:"大红灯笼高高挂", year:1991, duration:125,
      genres:["文艺","剧情"], moods:["calm","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:8.7,
      desc:"张艺谋早期高峰。乔家大院 + 巩俐 + 红灯笼。",
      tags:["张艺谋","巩俐"], poster:"🏮" },
    { id:"to-live", title:"活着", year:1994, duration:132,
      genres:["文艺","剧情"], moods:["down","calm"],
      weather:["any"], env:["dim","cool"], time:["evening"], people:[1],
      ageMin:16, ageMax:99, rating:9.3,
      desc:"葛优巩俐主演。余华小说 + 张艺谋，看完会安静一周。",
      tags:["张艺谋","葛优"], poster:"🐂" },
    { id:"i-love-you-cn", title:"我爱你！", year:2023, duration:120,
      genres:["爱情","家庭","文艺"], moods:["romantic","down","calm"],
      weather:["any"], env:["bright","cool"], time:["afternoon","evening"],
      people:[2,1,4], ageMin:14, ageMax:99, rating:7.2,
      desc:"韩延 × 倪大红惠英红。老年人也配轰轰烈烈。",
      tags:["催泪","老年爱情"], poster:"❤️" },
    { id:"under-the-hawthorn", title:"山楂树之恋", year:2010, duration:114,
      genres:["爱情","文艺"], moods:["romantic","calm","lonely"],
      weather:["any"], env:["cool","bright"], time:["afternoon"], people:[2,1],
      ageMin:14, ageMax:99, rating:7.1,
      desc:"张艺谋干净到不忍心的初恋故事。",
      tags:["张艺谋","纯爱"], poster:"🌸" },
    { id:"detective-chinatown", title:"唐人街探案", year:2015, duration:136,
      genres:["喜剧","悬疑","犯罪"], moods:["happy","curious"],
      weather:["any"], env:["bright"], time:["evening","night"],
      people:[3,4], ageMin:12, ageMax:99, rating:7.5,
      desc:"陈思诚悬疑喜剧起家。王宝强 + 刘昊然。",
      tags:["合家欢","悬疑"], poster:"🔎" },
    { id:"better-days", title:"少年的你", year:2019, duration:135,
      genres:["剧情","爱情"], moods:["down","stressed"],
      weather:["rainy","any"], env:["dim","cool"], time:["evening"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.2,
      desc:"曾国祥 × 周冬雨 × 易烊千玺。校园暴力题材。",
      tags:["现实题材"], poster:"📚" },
    { id:"so-long-my-son", title:"地久天长", year:2019, duration:185,
      genres:["文艺","家庭","剧情"], moods:["down","calm","lonely"],
      weather:["any"], env:["cool"], time:["afternoon","evening"], people:[1],
      ageMin:18, ageMax:99, rating:7.8,
      desc:"王小帅 30 年家庭跨度，后劲极大。",
      tags:["王小帅","柏林银熊"], poster:"🏚️" },
    { id:"yi-yi", title:"一一", year:2000, duration:173,
      genres:["文艺","家庭","剧情"], moods:["calm","lonely","down"],
      weather:["any"], env:["bright","cool"], time:["afternoon","evening"], people:[1],
      ageMin:18, ageMax:99, rating:9.0,
      desc:"杨德昌台湾家族画卷。看完想立刻给爸妈打电话。",
      tags:["杨德昌","华语经典"], poster:"👨‍👩‍👦" },
    { id:"a-brighter-summer-day", title:"牯岭街少年杀人事件", year:1991, duration:237,
      genres:["文艺","剧情"], moods:["down","curious"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:99, rating:8.9,
      desc:"杨德昌台湾青春史诗。",
      tags:["杨德昌"], poster:"🔦" },
    { id:"eat-drink-man-woman", title:"饮食男女", year:1994, duration:124,
      genres:["家庭","喜剧","治愈"], moods:["calm","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[4,1],
      ageMin:14, ageMax:99, rating:9.2,
      desc:"李安开场 10 分钟做饭名场面。看完想做羹汤。",
      tags:["李安","下饭"], poster:"🥢" },
    { id:"life-of-pi", title:"少年派的奇幻漂流", year:2012, duration:127,
      genres:["奇幻","冒险","文艺"], moods:["calm","curious","lonely"],
      weather:["any"], env:["dim","cool"], time:["evening","night"],
      people:[1,2,4], ageMin:10, ageMax:99, rating:9.1,
      desc:"李安老虎与男孩的太平洋。",
      tags:["李安","视效"], poster:"🐅" },
    { id:"brokeback-mountain", title:"断背山", year:2005, duration:134,
      genres:["爱情","文艺"], moods:["lonely","romantic","down"],
      weather:["any"], env:["dim","cool"], time:["evening","night"],
      people:[1,2], ageMin:18, ageMax:99, rating:8.8,
      desc:"李安。一句\"我多希望我知道怎么戒了你\"够心碎十年。",
      tags:["李安"], poster:"🏔️" },
    { id:"the-eight-hundred", title:"八佰", year:2020, duration:147,
      genres:["动作","剧情"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:99, rating:7.6,
      desc:"管虎四行仓库战争题材。",
      tags:["战争","国产"], poster:"🏚️" },
    { id:"nice-view", title:"奇迹·笨小孩", year:2022, duration:124,
      genres:["喜剧","剧情"], moods:["down","stressed"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,4],
      ageMin:10, ageMax:99, rating:6.9,
      desc:"易烊千玺打工奋斗。文牧野稳定发挥。",
      tags:["文牧野"], poster:"🧱" },
    { id:"sheep-without-a-shepherd", title:"误杀", year:2019, duration:112,
      genres:["悬疑","犯罪"], moods:["curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:99, rating:7.5,
      desc:"翻拍但完成度高。",
      tags:["国产悬疑"], poster:"🎞️" },
    { id:"banquet", title:"夜宴", year:2006, duration:131,
      genres:["剧情","动作","文艺"], moods:["calm","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:6.6,
      desc:"冯小刚版哈姆雷特。章子怡红裙起舞。",
      tags:["冯小刚"], poster:"👑" },
    { id:"american-dreams", title:"中国合伙人", year:2013, duration:131,
      genres:["剧情","喜剧"], moods:["down","happy"],
      weather:["any"], env:["bright"], time:["evening"], people:[3,1],
      ageMin:14, ageMax:99, rating:7.7,
      desc:"陈可辛 × 黄晓明邓超佟大为。新东方那点事。",
      tags:["励志"], poster:"🎓" },
    { id:"the-pig-the-snake", title:"周处除三害", year:2023, duration:134,
      genres:["动作","犯罪"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.2,
      desc:"阮经天封神之作。新造的人那段一秒不敢眨眼。",
      tags:["台湾","硬核"], poster:"🔪" },
    { id:"a-sun", title:"阳光普照", year:2019, duration:155,
      genres:["家庭","剧情","文艺"], moods:["down","calm"],
      weather:["sunny","any"], env:["bright","cool"], time:["afternoon","evening"],
      people:[1], ageMin:18, ageMax:99, rating:8.5,
      desc:"钟孟宏。看似平静的家，每个人都在自己的太阳下烧。",
      tags:["台湾","金马奖"], poster:"☀️" },
    { id:"farewell-my-yueyang", title:"地下铁", year:2003, duration:101,
      genres:["爱情","文艺"], moods:["lonely","romantic","calm"],
      weather:["rainy"], env:["dim","cool"], time:["evening","night"], people:[1,2],
      ageMin:16, ageMax:60, rating:7.4,
      desc:"梁朝伟 × 杨千嬅。地铁里的孤独和靠近。",
      tags:["港片","纯爱"], poster:"🚇" },
    { id:"a-city-of-sadness", title:"悲情城市", year:1989, duration:157,
      genres:["文艺","剧情"], moods:["calm","down"],
      weather:["any"], env:["dim"], time:["evening"], people:[1],
      ageMin:18, ageMax:99, rating:8.9,
      desc:"侯孝贤威尼斯金狮。一个时代的台湾家族肖像。",
      tags:["侯孝贤","金狮"], poster:"🏔️" },

    // ============ 日韩动画 / 真人 ============
    { id:"howls-castle", title:"哈尔的移动城堡", year:2004, duration:119,
      genres:["动画","奇幻","爱情","家庭"], moods:["romantic","calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["afternoon","evening"],
      people:[1,2,4], ageMin:8, ageMax:99, rating:8.9,
      desc:"宫崎骏 + 久石让。爱情让人长出魔法翅膀。",
      tags:["宫崎骏","治愈"], poster:"🏯" },
    { id:"princess-mononoke", title:"幽灵公主", year:1997, duration:134,
      genres:["动画","奇幻","冒险"], moods:["curious","calm"],
      weather:["any"], env:["dim","cool"], time:["evening"], people:[1,4],
      ageMin:10, ageMax:99, rating:8.9,
      desc:"宫崎骏。森林与人的史诗对决。",
      tags:["宫崎骏","环保"], poster:"🐺" },
    { id:"ponyo", title:"悬崖上的金鱼姬", year:2008, duration:101,
      genres:["动画","家庭","奇幻","治愈"], moods:["happy","calm"],
      weather:["any"], env:["bright"], time:["afternoon"], people:[4,1],
      ageMin:3, ageMax:99, rating:8.4,
      desc:"宫崎骏给小朋友的童话。",
      tags:["宫崎骏","亲子"], poster:"🐟" },
    { id:"weathering-with-you", title:"天气之子", year:2019, duration:114,
      genres:["动画","爱情","奇幻"], moods:["romantic","lonely"],
      weather:["rainy"], env:["dim","cool"], time:["evening","night"],
      people:[1,2], ageMin:12, ageMax:60, rating:7.7,
      desc:"新海诚雨天专属。",
      tags:["新海诚","雨天"], poster:"☔" },
    { id:"suzume", title:"铃芽之旅", year:2022, duration:122,
      genres:["动画","奇幻","冒险"], moods:["calm","curious","down"],
      weather:["any"], env:["bright","cool"], time:["afternoon","evening"],
      people:[1,2], ageMin:10, ageMax:60, rating:7.4,
      desc:"新海诚地震主题。",
      tags:["新海诚"], poster:"🚪" },
    { id:"the-boy-and-the-heron", title:"你想活出怎样的人生", year:2023, duration:124,
      genres:["动画","奇幻","家庭"], moods:["curious","calm"],
      weather:["any"], env:["dim","cool"], time:["evening","night"],
      people:[1,4], ageMin:10, ageMax:99, rating:7.8,
      desc:"宫崎骏可能的告别作。",
      tags:["宫崎骏","奥斯卡"], poster:"🪶" },
    { id:"a-silent-voice", title:"声之形", year:2016, duration:130,
      genres:["动画","爱情","剧情"], moods:["down","lonely","romantic"],
      weather:["any"], env:["cool"], time:["evening","night"], people:[1,2],
      ageMin:13, ageMax:60, rating:8.5,
      desc:"京阿尼。校园霸凌后的救赎。",
      tags:["京阿尼","催泪"], poster:"🤟" },
    { id:"eat-your-pancreas", title:"我想吃掉你的胰脏", year:2018, duration:108,
      genres:["动画","爱情","剧情"], moods:["romantic","down","lonely"],
      weather:["any"], env:["cool"], time:["evening","night"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.2,
      desc:"标题猎奇但内容是纯爱催泪炸弹。",
      tags:["催泪"], poster:"🌸" },
    { id:"5cm-per-second", title:"秒速五厘米", year:2007, duration:63,
      genres:["动画","爱情","文艺"], moods:["lonely","romantic","down"],
      weather:["snowy","cold"], env:["cool","dim"], time:["evening","night"],
      people:[1], ageMin:14, ageMax:99, rating:7.7,
      desc:"新海诚早期。樱花落下的速度，是 5 厘米每秒。",
      tags:["新海诚","短片"], poster:"🌸" },
    { id:"the-wind-rises", title:"起风了", year:2013, duration:126,
      genres:["动画","爱情","剧情"], moods:["calm","lonely","romantic"],
      weather:["any"], env:["cool","bright"], time:["afternoon","evening"],
      people:[1,2], ageMin:14, ageMax:99, rating:8.2,
      desc:"宫崎骏献给堀辰雄。\"起风了，唯有努力生存。\"",
      tags:["宫崎骏"], poster:"🛩️" },
    { id:"only-yesterday", title:"岁月的童话", year:1991, duration:118,
      genres:["动画","家庭","治愈"], moods:["calm","lonely","down"],
      weather:["any"], env:["bright"], time:["afternoon"], people:[1],
      ageMin:14, ageMax:99, rating:8.7,
      desc:"高畑勋。27 岁看 10 岁的自己，安静得想哭。",
      tags:["吉卜力","治愈"], poster:"🌾" },
    { id:"summer-wars", title:"夏日大作战", year:2009, duration:114,
      genres:["动画","奇幻","家庭","冒险"], moods:["happy","excited"],
      weather:["hot","sunny"], env:["bright","hot"], time:["afternoon","evening"],
      people:[4,3], ageMin:10, ageMax:99, rating:8.4,
      desc:"细田守。夏日 + 家族 + 网络危机。",
      tags:["细田守","夏天必看"], poster:"🍉" },
    { id:"belle", title:"龙与雀斑公主", year:2021, duration:122,
      genres:["动画","奇幻","爱情"], moods:["lonely","romantic","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,2],
      ageMin:12, ageMax:60, rating:7.4,
      desc:"细田守 × 中村佳穗。互联网世界里的美女与野兽。",
      tags:["细田守"], poster:"🐉" },
    { id:"perfect-blue", title:"未麻的部屋", year:1997, duration:81,
      genres:["动画","悬疑","恐怖"], moods:["curious","stressed"],
      weather:["any"], env:["dim"], time:["latenight"], people:[1],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"今敏 cult 神作。看完会怀疑哪个自己是真的。",
      tags:["今敏","烧脑"], poster:"💄" },
    { id:"tokyo-godfathers", title:"东京教父", year:2003, duration:92,
      genres:["动画","喜剧","家庭"], moods:["calm","happy","down"],
      weather:["snowy","cold"], env:["cool","dim"], time:["evening","night"],
      people:[1,4], ageMin:12, ageMax:99, rating:8.6,
      desc:"今敏圣诞奇迹。三个流浪汉捡到一个小婴儿。",
      tags:["今敏","圣诞片"], poster:"👼" },
    { id:"departures", title:"入殓师", year:2008, duration:130,
      genres:["剧情","治愈","文艺"], moods:["calm","down","lonely"],
      weather:["snowy","cold","any"], env:["cool"], time:["evening"],
      people:[1], ageMin:14, ageMax:99, rating:8.9,
      desc:"奥斯卡最佳外语片。久石让 + 大提琴 + 雪国。",
      tags:["治愈","奥斯卡"], poster:"🎻" },
    { id:"shoplifters", title:"小偷家族", year:2018, duration:121,
      genres:["家庭","剧情","文艺"], moods:["calm","down","lonely"],
      weather:["any"], env:["cool"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:8.7,
      desc:"是枝裕和金棕榈。一家人是被血缘拴住，还是被选择？",
      tags:["是枝裕和","金棕榈"], poster:"🥟" },
    { id:"like-father-like-son", title:"如父如子", year:2013, duration:120,
      genres:["家庭","剧情","治愈"], moods:["calm","down"],
      weather:["any"], env:["cool","bright"], time:["afternoon","evening"],
      people:[1,4], ageMin:14, ageMax:99, rating:8.7,
      desc:"是枝裕和。抱错的孩子，重新定义父亲。",
      tags:["是枝裕和"], poster:"👨‍👦" },
    { id:"still-walking", title:"步履不停", year:2008, duration:114,
      genres:["家庭","文艺"], moods:["calm","lonely"],
      weather:["any"], env:["bright","cool"], time:["afternoon"], people:[1,4],
      ageMin:18, ageMax:99, rating:8.8,
      desc:"是枝裕和。家人聚一餐，半生重量轻轻落下。",
      tags:["是枝裕和","治愈"], poster:"🍵" },
    { id:"oldboy", title:"老男孩", year:2003, duration:120,
      genres:["悬疑","犯罪","动作"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1],
      ageMin:18, ageMax:60, rating:8.2,
      desc:"朴赞郁复仇三部曲。走廊单镜头打架打到出圈。",
      tags:["朴赞郁"], poster:"🔨" },
    { id:"the-handmaiden", title:"小姐", year:2016, duration:144,
      genres:["悬疑","爱情","文艺"], moods:["curious","romantic"],
      weather:["any"], env:["dim"], time:["night"], people:[1,2],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"朴赞郁。三段反转 + 美术爆表。",
      tags:["朴赞郁","视觉"], poster:"🗝️" },
    { id:"the-chaser", title:"追击者", year:2008, duration:125,
      genres:["悬疑","犯罪","动作"], moods:["excited","stressed"],
      weather:["rainy","any"], env:["dim"], time:["night","latenight"],
      people:[1,3], ageMin:18, ageMax:60, rating:8.4,
      desc:"罗泓轸 × 河正宇。韩国悬疑高地的开端。",
      tags:["韩国"], poster:"🚔" },
    { id:"the-wailing", title:"哭声", year:2016, duration:156,
      genres:["恐怖","悬疑"], moods:["curious"],
      weather:["rainy","any"], env:["dim"], time:["latenight","night"], people:[1],
      ageMin:18, ageMax:55, rating:8.0,
      desc:"罗泓轸。韩国恐怖片天花板。",
      tags:["韩国","cult"], poster:"🪦" },
    { id:"train-to-busan", title:"釜山行", year:2016, duration:118,
      genres:["恐怖","动作","冒险"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,1],
      ageMin:16, ageMax:60, rating:8.5,
      desc:"延尚昊。一列火车开向釜山，也开向人性深处。",
      tags:["韩国","丧尸"], poster:"🚄" },
    { id:"silenced", title:"熔炉", year:2011, duration:125,
      genres:["剧情"], moods:["down","stressed"],
      weather:["any"], env:["dim","cool"], time:["evening"], people:[1],
      ageMin:18, ageMax:60, rating:9.3,
      desc:"孔刘演完推动韩国修法。看完会沉默一周。",
      tags:["韩国","社会题材"], poster:"⚖️" },
    { id:"cell-no-7", title:"7号房的礼物", year:2013, duration:127,
      genres:["剧情","家庭","喜剧"], moods:["down"],
      weather:["any"], env:["bright"], time:["evening"], people:[4,1],
      ageMin:10, ageMax:99, rating:8.7,
      desc:"亲子催泪炸弹。前半笑哈哈，后半抠纸巾。",
      tags:["催泪","韩国"], poster:"🎈" },
    { id:"poetry", title:"诗", year:2010, duration:139,
      genres:["文艺","剧情"], moods:["calm","lonely","down"],
      weather:["any"], env:["bright","cool"], time:["afternoon"], people:[1],
      ageMin:18, ageMax:99, rating:8.5,
      desc:"李沧东。一位奶奶想要写一首诗。",
      tags:["李沧东"], poster:"📝" },
    { id:"burning", title:"燃烧", year:2018, duration:148,
      genres:["悬疑","文艺"], moods:["lonely","curious"],
      weather:["any"], env:["dim","cool"], time:["evening","night"],
      people:[1], ageMin:18, ageMax:60, rating:7.8,
      desc:"李沧东 × 村上春树。火光暧昧。",
      tags:["李沧东","村上春树"], poster:"🔥" },
    { id:"hope", title:"素媛", year:2013, duration:122,
      genres:["剧情","家庭"], moods:["down"],
      weather:["any"], env:["cool"], time:["evening"], people:[1],
      ageMin:18, ageMax:60, rating:9.3,
      desc:"李濬益。每一个父亲都该看一次。",
      tags:["韩国","催泪"], poster:"🎗️" },
    { id:"new-world", title:"新世界", year:2013, duration:135,
      genres:["犯罪","动作","悬疑"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["night"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.6,
      desc:"朴勋政。\"我是来谈合作的\"，李政宰黑化是真帅。",
      tags:["韩国","黑帮"], poster:"🕴️" },
    { id:"yellow-sea", title:"黄海", year:2010, duration:140,
      genres:["动作","犯罪"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["night"], people:[1],
      ageMin:18, ageMax:55, rating:8.3,
      desc:"罗泓轸。河正宇逃亡 + 金允石追杀。",
      tags:["韩国","硬核"], poster:"🪓" },
    { id:"miss-granny", title:"奇怪的她", year:2014, duration:124,
      genres:["喜剧","奇幻","家庭"], moods:["happy","down"],
      weather:["any"], env:["bright"], time:["evening"], people:[4,3,1],
      ageMin:10, ageMax:99, rating:8.4,
      desc:"沈恩京演奶奶变 20 岁少女。一边笑一边哭。",
      tags:["韩国","催泪"], poster:"📷" },
    { id:"my-sassy-girl", title:"我的野蛮女友", year:2001, duration:137,
      genres:["爱情","喜剧"], moods:["romantic","happy"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[1,2],
      ageMin:14, ageMax:60, rating:8.5,
      desc:"全智贤封神。\"对不起，让你久等了\"。",
      tags:["韩国","纯爱"], poster:"💌" },
    { id:"il-mare", title:"触不到的恋人", year:2000, duration:96,
      genres:["爱情","奇幻","文艺"], moods:["romantic","lonely"],
      weather:["rainy","any"], env:["dim","cool"], time:["evening","night"],
      people:[1,2], ageMin:14, ageMax:60, rating:7.6,
      desc:"全智贤 × 李政宰。海边的木屋，跨时空的信。",
      tags:["韩国","纯爱"], poster:"📮" },
    { id:"shin-godzilla", title:"新哥斯拉", year:2016, duration:120,
      genres:["科幻","冒险","动作"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,1],
      ageMin:12, ageMax:60, rating:7.6,
      desc:"庵野秀明。这次哥斯拉吃的是日本官僚体制。",
      tags:["怪兽片"], poster:"🦖" },
    { id:"drive-my-car", title:"驾驶我的车", year:2021, duration:179,
      genres:["文艺","剧情"], moods:["calm","lonely"],
      weather:["any"], env:["cool","dim"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:99, rating:7.6,
      desc:"滨口龙介 × 村上春树。三小时的车内独白。",
      tags:["滨口龙介","奥斯卡"], poster:"🚗" },

    // ============ 欧美爆米花 / 动作 / 科幻（前半） ============
    { id:"the-dark-knight", title:"蝙蝠侠：黑暗骑士", year:2008, duration:152,
      genres:["动作","犯罪","悬疑"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:9.2,
      desc:"诺兰 × 希斯·莱杰。Joker 是漫改最强反派。",
      tags:["诺兰","DC"], poster:"🦇" },
    { id:"dunkirk", title:"敦刻尔克", year:2017, duration:106,
      genres:["剧情","动作"], moods:["stressed","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:12, ageMax:60, rating:8.4,
      desc:"诺兰战争片。三条时间线像扣表。",
      tags:["诺兰","战争"], poster:"⛴️" },
    { id:"tenet", title:"信条", year:2020, duration:150,
      genres:["科幻","动作","悬疑"], moods:["curious","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:7.6,
      desc:"诺兰。\"不要试图理解它，去感受它\"。",
      tags:["诺兰","烧脑"], poster:"⏳" },
    { id:"oppenheimer", title:"奥本海默", year:2023, duration:180,
      genres:["剧情","文艺"], moods:["curious","stressed"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:8.8,
      desc:"诺兰。三小时人脸特写，火也不够烫。",
      tags:["诺兰","奥斯卡"], poster:"☢️" },
    { id:"the-matrix", title:"黑客帝国", year:1999, duration:136,
      genres:["科幻","动作"], moods:["curious","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:9.0,
      desc:"沃卓斯基。红色药丸还是蓝色药丸？",
      tags:["科幻经典","赛博朋克"], poster:"💊" },
    { id:"truman-show", title:"楚门的世界", year:1998, duration:103,
      genres:["剧情","科幻","喜剧"], moods:["curious","down"],
      weather:["any"], env:["bright"], time:["evening"], people:[1,2],
      ageMin:12, ageMax:99, rating:9.4,
      desc:"如果你也怀疑过整个世界是片场。",
      tags:["金凯瑞","哲学"], poster:"🌅" },
    { id:"forrest-gump", title:"阿甘正传", year:1994, duration:142,
      genres:["剧情","爱情","治愈"], moods:["down","calm","happy"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1,4],
      ageMin:10, ageMax:99, rating:9.5,
      desc:"\"生活就像一盒巧克力\"，跑就完了。",
      tags:["奥斯卡","治愈"], poster:"🍫" },
    { id:"shawshank", title:"肖申克的救赎", year:1994, duration:142,
      genres:["剧情","治愈"], moods:["down","calm","lonely"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:14, ageMax:99, rating:9.7,
      desc:"豆瓣榜首 20 年。希望是好东西，也许是世上最好的。",
      tags:["神片","励志"], poster:"🪨" },
    { id:"green-mile", title:"绿里奇迹", year:1999, duration:189,
      genres:["剧情","奇幻"], moods:["down","calm","lonely"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:9.2,
      desc:"达拉邦特再下一城。三小时却像 30 分钟。",
      tags:["奇幻","催泪"], poster:"🟢" },
    { id:"saving-private-ryan", title:"拯救大兵瑞恩", year:1998, duration:169,
      genres:["剧情","动作"], moods:["stressed","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:16, ageMax:60, rating:9.1,
      desc:"斯皮尔伯格诺曼底登陆。开场 25 分钟是教科书。",
      tags:["斯皮尔伯格","战争"], poster:"🪖" },
    { id:"schindlers-list", title:"辛德勒的名单", year:1993, duration:195,
      genres:["剧情","文艺"], moods:["down","calm"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:9.5,
      desc:"斯皮尔伯格黑白史诗。红衣小女孩永远忘不掉。",
      tags:["斯皮尔伯格","奥斯卡"], poster:"🕯️" },
    { id:"pulp-fiction", title:"低俗小说", year:1994, duration:154,
      genres:["犯罪","喜剧"], moods:["curious","excited"],
      weather:["any"], env:["dim"], time:["night","latenight"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.9,
      desc:"昆汀的多线叙事开山作。",
      tags:["昆汀","邪典"], poster:"🍔" },
    { id:"inglourious-basterds", title:"无耻混蛋", year:2009, duration:153,
      genres:["剧情","动作"], moods:["excited"],
      weather:["any"], env:["dim"], time:["night"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.6,
      desc:"昆汀改写二战。开场 20 分钟牛奶场戏。",
      tags:["昆汀","战争"], poster:"🥛" },
    { id:"once-upon-hollywood", title:"好莱坞往事", year:2019, duration:161,
      genres:["剧情","喜剧"], moods:["calm","curious"],
      weather:["any"], env:["bright"], time:["afternoon","evening"], people:[1],
      ageMin:18, ageMax:60, rating:7.5,
      desc:"昆汀给老好莱坞的情书。",
      tags:["昆汀","情怀"], poster:"📽️" },
    { id:"goodfellas", title:"好家伙", year:1990, duration:146,
      genres:["犯罪","剧情"], moods:["curious","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.7,
      desc:"斯科塞斯黑帮三部曲之一。",
      tags:["斯科塞斯"], poster:"🎰" },
    { id:"godfather", title:"教父", year:1972, duration:175,
      genres:["剧情","犯罪"], moods:["calm","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:9.3,
      desc:"\"我会给他一个无法拒绝的提议\"。",
      tags:["神片","经典"], poster:"🍷" },
    { id:"godfather-2", title:"教父2", year:1974, duration:202,
      genres:["剧情","犯罪"], moods:["calm","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:99, rating:9.2,
      desc:"少有的续集超越前作。",
      tags:["神片","续集"], poster:"🥃" },
    { id:"taxi-driver", title:"出租车司机", year:1976, duration:114,
      genres:["剧情","犯罪"], moods:["lonely","down"],
      weather:["rainy","any"], env:["dim"], time:["latenight"], people:[1],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"\"You talking to me?\" 孤独教科书。",
      tags:["斯科塞斯","cult"], poster:"🚕" },
    { id:"joker", title:"小丑", year:2019, duration:122,
      genres:["剧情","悬疑"], moods:["down","lonely"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:8.6,
      desc:"杰昆封神。看完想冲楼下踩猫，但请别。",
      tags:["DC","奥斯卡"], poster:"🤡" },
    { id:"avatar", title:"阿凡达", year:2009, duration:162,
      genres:["科幻","冒险"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4,2],
      ageMin:10, ageMax:99, rating:8.8,
      desc:"卡梅隆潘多拉。",
      tags:["视效","卡梅隆"], poster:"🌳" },
    { id:"avatar-water", title:"阿凡达：水之道", year:2022, duration:192,
      genres:["科幻","冒险"], moods:["excited","calm"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4],
      ageMin:10, ageMax:99, rating:7.7,
      desc:"卡梅隆水底视效。",
      tags:["卡梅隆"], poster:"🐋" },
    { id:"titanic", title:"泰坦尼克号", year:1997, duration:194,
      genres:["爱情","剧情"], moods:["romantic","down"],
      weather:["cold","snowy"], env:["dim","cool"], time:["evening","night"],
      people:[2,1], ageMin:14, ageMax:99, rating:9.5,
      desc:"\"You jump, I jump\"，三十年不过时。",
      tags:["卡梅隆","经典"], poster:"🚢" },
    { id:"avengers-endgame", title:"复仇者联盟4：终局之战", year:2019, duration:182,
      genres:["动作","冒险","科幻"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4,1],
      ageMin:10, ageMax:60, rating:8.4,
      desc:"漫威 10 年终局。\"I am Iron Man\"。",
      tags:["漫威"], poster:"🛡️" },
    { id:"guardians", title:"银河护卫队", year:2014, duration:121,
      genres:["科幻","冒险","喜剧"], moods:["happy","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4,1],
      ageMin:10, ageMax:60, rating:8.1,
      desc:"漫威最贱嘴 5 人组 + 70 年代金曲。",
      tags:["漫威","BGM"], poster:"🚀" },
    { id:"spiderman-no-way-home", title:"蜘蛛侠：英雄无归", year:2021, duration:148,
      genres:["动作","科幻","冒险"], moods:["happy","excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4],
      ageMin:8, ageMax:60, rating:8.2,
      desc:"三代蜘蛛侠合体。情怀拉满。",
      tags:["漫威"], poster:"🕸️" },
    { id:"mi-6-fallout", title:"碟中谍6：全面瓦解", year:2018, duration:147,
      genres:["动作","冒险"], moods:["excited"],
      weather:["any"], env:["bright","dim"], time:["evening","night"], people:[1,3],
      ageMin:12, ageMax:60, rating:8.2,
      desc:"阿汤哥 56 岁亲自跳伞。爽片标杆。",
      tags:["阿汤哥","爆米花"], poster:"🪂" },
    { id:"mi-7", title:"碟中谍7：致命清算", year:2023, duration:163,
      genres:["动作","冒险"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:12, ageMax:60, rating:7.7,
      desc:"60 岁阿汤哥还在飞悬崖。",
      tags:["阿汤哥"], poster:"🏍️" },
    { id:"casino-royale", title:"007：大战皇家赌场", year:2006, duration:144,
      genres:["动作","冒险"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:7.7,
      desc:"丹尼尔·克雷格首部 007。",
      tags:["007"], poster:"🎰" },
    { id:"skyfall", title:"007：大破天幕杀机", year:2012, duration:143,
      genres:["动作","冒险"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:7.7,
      desc:"门德斯执导，007 系列影像最美一部。",
      tags:["007"], poster:"🍸" },
    { id:"jurassic-park", title:"侏罗纪公园", year:1993, duration:127,
      genres:["科幻","冒险","家庭"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,4],
      ageMin:10, ageMax:60, rating:8.3,
      desc:"30 年前的特效现在还能打。",
      tags:["斯皮尔伯格"], poster:"🦕" },
    { id:"et", title:"E.T. 外星人", year:1982, duration:115,
      genres:["科幻","家庭","治愈"], moods:["calm","happy","down"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[4,1],
      ageMin:6, ageMax:99, rating:8.7,
      desc:"斯皮尔伯格永远的童心。",
      tags:["斯皮尔伯格"], poster:"👽" },
    { id:"back-to-future", title:"回到未来", year:1985, duration:116,
      genres:["科幻","喜剧","冒险"], moods:["happy","excited","curious"],
      weather:["any"], env:["bright"], time:["evening"], people:[3,4],
      ageMin:8, ageMax:99, rating:8.9,
      desc:"DeLorean + 88 mph，永远爽。",
      tags:["经典","合家欢"], poster:"🚗" },
    { id:"alien", title:"异形", year:1979, duration:117,
      genres:["科幻","恐怖"], moods:["excited","curious"],
      weather:["any"], env:["dim"], time:["latenight","night"], people:[1,3],
      ageMin:18, ageMax:60, rating:8.4,
      desc:"雷德利·斯科特。深空 + 紧闭 + 你不知道下一秒怎么死。",
      tags:["科幻经典"], poster:"👾" },
    { id:"aliens", title:"异形2", year:1986, duration:137,
      genres:["科幻","动作"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:16, ageMax:60, rating:8.4,
      desc:"卡梅隆动作版。",
      tags:["卡梅隆","硬核"], poster:"🤖" },
    { id:"terminator-2", title:"终结者2：审判日", year:1991, duration:137,
      genres:["科幻","动作"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:8.7,
      desc:"卡梅隆 + 施瓦辛格。I'll be back。",
      tags:["卡梅隆"], poster:"🤖" },
    { id:"die-hard", title:"虎胆龙威", year:1988, duration:131,
      genres:["动作"], moods:["excited","happy"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,1],
      ageMin:14, ageMax:60, rating:8.4,
      desc:"圣诞动作片祖师爷。",
      tags:["圣诞","硬汉"], poster:"🎄" },
    { id:"the-rock", title:"勇闯夺命岛", year:1996, duration:136,
      genres:["动作","冒险"], moods:["excited"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[3,1],
      ageMin:14, ageMax:60, rating:8.2,
      desc:"康纳利 + 凯奇 + 监狱大反攻。",
      tags:["爽片","90s"], poster:"🪨" },
    { id:"speed", title:"生死时速", year:1994, duration:116,
      genres:["动作","冒险"], moods:["excited","stressed"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[3,1],
      ageMin:12, ageMax:60, rating:8.0,
      desc:"基努 × 桑德拉 × 一辆不能停的公交。",
      tags:["爽片","经典"], poster:"🚌" },
    { id:"fast-five", title:"速度与激情5", year:2011, duration:130,
      genres:["动作","犯罪"], moods:["excited","happy"],
      weather:["hot","sunny"], env:["bright","hot"], time:["evening","night"],
      people:[3], ageMin:12, ageMax:50, rating:7.3,
      desc:"速激系列拐弯成功的一部。",
      tags:["爽片"], poster:"🏎️" },
    { id:"transformers-1", title:"变形金刚", year:2007, duration:144,
      genres:["科幻","动作","冒险"], moods:["excited","happy"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[3,4],
      ageMin:10, ageMax:60, rating:8.1,
      desc:"麦昆 BGM 一响童年就回来。",
      tags:["视效","童年"], poster:"🚙" },
    { id:"baby-driver", title:"极盗车神", year:2017, duration:113,
      genres:["动作","犯罪"], moods:["excited","happy"],
      weather:["any"], env:["bright"], time:["evening","night"], people:[1,3],
      ageMin:16, ageMax:60, rating:7.7,
      desc:"埃德加·赖特剪辑神片。",
      tags:["剪辑","BGM"], poster:"🎧" },
    { id:"sicario", title:"边境杀手", year:2015, duration:121,
      genres:["犯罪","动作","悬疑"], moods:["stressed","curious"],
      weather:["hot","sunny"], env:["dim","hot"], time:["evening","night"], people:[1],
      ageMin:18, ageMax:60, rating:7.7,
      desc:"维伦纽瓦。墨西哥毒战，心率飙升。",
      tags:["维伦纽瓦"], poster:"🌵" },
    { id:"dune", title:"沙丘", year:2021, duration:155,
      genres:["科幻","冒险"], moods:["calm","curious"],
      weather:["hot","sunny"], env:["dim","hot"], time:["evening","night"],
      people:[1,3], ageMin:14, ageMax:60, rating:7.8,
      desc:"维伦纽瓦。沙虫一出 IMAX 厅都在颤。",
      tags:["维伦纽瓦","视效"], poster:"🏜️" },
    { id:"dune-2", title:"沙丘2", year:2024, duration:166,
      genres:["科幻","冒险","动作"], moods:["excited","calm"],
      weather:["hot","sunny"], env:["dim"], time:["evening","night"], people:[1,3],
      ageMin:14, ageMax:60, rating:8.3,
      desc:"沙丘续作。封神之路稳了。",
      tags:["维伦纽瓦"], poster:"🐛" },
    { id:"blade-runner-2049", title:"银翼杀手2049", year:2017, duration:163,
      genres:["科幻","悬疑","文艺"], moods:["lonely","calm","curious"],
      weather:["rainy","any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:60, rating:8.4,
      desc:"维伦纽瓦 + 罗杰·迪金斯。每一帧能挂卢浮宫。",
      tags:["维伦纽瓦","赛博朋克"], poster:"☔" },
    { id:"ex-machina", title:"机械姬", year:2014, duration:108,
      genres:["科幻","悬疑"], moods:["curious"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1,2],
      ageMin:16, ageMax:60, rating:7.8,
      desc:"小成本 AI 神片。",
      tags:["AI"], poster:"🤖" },
    { id:"her", title:"她", year:2013, duration:126,
      genres:["科幻","爱情","文艺"], moods:["lonely","romantic","calm"],
      weather:["any"], env:["dim","cool"], time:["evening","night"], people:[1],
      ageMin:16, ageMax:60, rating:8.5,
      desc:"和 AI 谈一场恋爱，2025 看更扎心。",
      tags:["AI","文艺"], poster:"📱" },
    { id:"social-network", title:"社交网络", year:2010, duration:120,
      genres:["剧情"], moods:["curious"],
      weather:["any"], env:["dim"], time:["evening"], people:[1],
      ageMin:14, ageMax:60, rating:8.1,
      desc:"芬奇 × 索金。Facebook 起家。",
      tags:["芬奇","传记"], poster:"💻" },
    { id:"whiplash", title:"爆裂鼓手", year:2014, duration:107,
      genres:["剧情"], moods:["excited","stressed"],
      weather:["any"], env:["dim"], time:["evening","night"], people:[1],
      ageMin:14, ageMax:60, rating:8.7,
      desc:"\"Not quite my tempo\"，鸡皮疙瘩。",
      tags:["音乐","硬核"], poster:"🥁" },
    { id:"three-billboards", title:"三块广告牌", year:2017, duration:115,
      genres:["剧情","犯罪","喜剧"], moods:["down","curious"],
      weather:["any"], env:["bright","cool"], time:["evening"], people:[1],
      ageMin:18, ageMax:60, rating:8.7,
      desc:"麦克唐纳。失去女儿的母亲杠上整个小镇。",
      tags:["奥斯卡","黑色喜剧"], poster:"🪧" }
  ];

  window.MOVIES.push(...EXTRA);
})();
